using Newtonsoft.Json;

namespace PayU.Models.Base.Subcomponents
{
    /// <summary>
    /// Defines the 3DS 2.0 data.
    /// This object does not replace the card information or the required fields to start a transaction. This object is additional.
    /// This object corresponds to a Pass Through scenario where the shop performs the 3DS Authentication on its own.
    /// Currently, this scenario is only available for Colombia and Brazil.
    /// </summary>
    public class ThreeDomainSecure
    {
        /// <summary>
        /// Indicates whether an internal (embedded) MPI must be used for authorization process.
        /// If no value is provided, "false" is used as default.
        /// </summary>
        [JsonProperty("embedded")]
        public bool Embedded { get; set; }
        
        /// <summary>
        /// Electronic Commerce Indicator.
        /// Value returned by Directory Servers indicating the outcome of attempted authentication.
        /// It is mandatory when Embedded is false and XID is present.
        /// </summary>
        [JsonProperty("eci")]
        public int ECI { get; set; }
        
        /// <summary>
        /// Cardholder Authentication Verification Value.
        /// Base64 encoded string.
        /// Code of the cryptogram used in the transaction authentication.
        /// Depending on specific ECI codes set by the network, this field must be sent or not.
        /// </summary>
        [JsonProperty("cavv")]
        public string CAVV { get; set; }
        
        /// <summary>
        /// ID of the authentication transaction sent by the MPI.
        /// Base64 encoded string.
        /// It is mandatory when Embedded is false and ECI is present.
        /// </summary>
        [JsonProperty("xid")]
        public string XID { get; set; }
        
        /// <summary>
        /// Transaction ID generated by Directory Server during authentication.
        /// This field is not required to be sent by some networks but it is a best practice to provide this when 3DS is used.
        /// </summary>
        [JsonProperty("directoryServerTransactionId")]
        public string DSTID { get; set; }
    }
}